version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION} # 3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION} # 1.0
    ports:
      - target: 9292 # the port inside the container
        published: ${PUBLIC_PORT} # the publicly exposed port
        protocol: tcp # the port protocol (tcp or udp)
        mode: host # host for publishing a host port on each node, or ingress for a swarm mode port to be load balanced.
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION} # 1.0
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION} # 1.0
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

  # prometheus:
  #   image: ${USERNAME}/prometheus
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--storage.tsdb.retention=1d'
  #   networks:
  #     front_net:
  #       aliases:
  #         - prometheus
  #     back_net:
  #       aliases:
  #         - prometheus

  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     front_net:
  #       aliases:
  #         - node_exporter
  #     back_net:
  #       aliases:
  #         - node_exporter

  # mongodb-exporter:
  #   image: ${USERNAME}/mongodb-exporter:${MONGO_EXPORTER_VERSION}
  #   ports:
  #     - '9216:9216'
  #   command:
  #     - '--collect.database'
  #     - '--collect.collection'
  #     - '--collect.indexusage'
  #     - '--collect.topmetrics'
  #     - '--mongodb.uri=mongodb://post_db:27017'
  #   networks:
  #     back_net:
  #       aliases:
  #         - mongodb-exporter

  # blackbox-exporter:
  #   image: ${USERNAME}/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}
  #   ports:
  #     - '9115:9115'
  #   networks:
  #     back_net:
  #       aliases:
  #         - blackbox-exporter

  #     front_net:
  #       aliases:
  #         - blackbox-exporter

volumes:
  post_db:
  # prometheus_data:
networks:
#   reddit:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
