version: '3.3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      front_net:
        aliases:
          - fluentd
      back_net:
        aliases:
          - fluentd

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      front_net:
        aliases:
          - elasticsearch
      back_net:
        aliases:
          - elasticsearch
  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"
    networks:
      front_net:
        aliases:
          - kibana
      back_net:
        aliases:
          - kibana

  zipkin:
    image: openzipkin/zipkin:${ZIPKIN_VERSION}
    ports:
      - "9411:9411"
    networks:
      front_net:
        aliases:
          - zipkin
      back_net:
        aliases:
          - zipkin

networks:
#   reddit:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
