version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION} # 3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION} # 1.0
    ports:
      - target: 9292 # the port inside the container
        published: ${PUBLIC_PORT} # the publicly exposed port
        protocol: tcp # the port protocol (tcp or udp)
        mode: host # host for publishing a host port on each node, or ingress for a swarm mode port to be load balanced.
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION} # 1.0
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION} # 1.0
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
#   reddit:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
